### PR TITLE
 FIX Embed Color and Channel Emoji

### PR DESCRIPTION
**Pull request by Musiker15**
* FIX Embed Color and Channel Emoji
* Added Debian/Ubuntu Installation Guide

### CODE REVIEW

**Comment by ghost** [comment]
I tried to contact the dev of this bot to talk about the bugs but he bans me for no reason from his discord server I do not recommend

**Comment by Musiker15** [comment]
I'm not the Dev of this bot! Why you posting that in this pull request?

**Comment by ghost** [comment]
I allow myself to post this here because you are banning me from your discord server for no reason so I invite you to review the code of the script that you yourself modified the lines and make it "usable" in + on your MSK Script bot on bot works as it should why not modify the code to make it usable
 ?

**Comment by ghost** [comment]
I nevertheless approached you with sympathy in mp discord to report the errors of the script

**Review by Lastshot0001 — APPROVED** [review]

**Pull request merged**
